import { SetStatus, ProjectStatus } from '../types';

export const STATUS_LABELS: Record<SetStatus, string> = {
  owned: '已有',
  building: '在建',
  completed: '已完成',
  disassembled: '已拆散',
  wishlist: '愿望清单',
};

export const STATUS_COLORS: Record<SetStatus, string> = {
  owned: 'bg-emerald-100 text-emerald-700',
  building: 'bg-amber-100 text-amber-700',
  completed: 'bg-blue-100 text-blue-700',
  disassembled: 'bg-gray-100 text-gray-700',
  wishlist: 'bg-pink-100 text-pink-700',
};

export const PROJECT_STATUS_LABELS: Record<ProjectStatus, string> = {
  planning: '规划中',
  in_progress: '进行中',
  completed: '已完成',
};

export const PROJECT_STATUS_COLORS: Record<ProjectStatus, string> = {
  planning: 'bg-purple-100 text-purple-700',
  in_progress: 'bg-amber-100 text-amber-700',
  completed: 'bg-green-100 text-green-700',
};

export const INVENTORY_SOURCE_LABELS: Record<string, string> = {
  set: '套装拆出',
  spare: '备用零件',
  purchase: '购买',
  other: '其他',
};

export const INVENTORY_SOURCE_COLORS: Record<string, string> = {
  set: 'bg-lego-blue/10 text-lego-blue',
  spare: 'bg-lego-yellow/20 text-amber-700',
  purchase: 'bg-lego-red/10 text-lego-red',
  other: 'bg-gray-100 text-gray-700',
};

export const CHART_COLORS = [
  '#E3000B',
  '#FFD500',
  '#0A2463',
  '#10B981',
  '#F59E0B',
  '#8B5CF6',
  '#EC4899',
  '#06B6D4',
  '#84CC16',
  '#F97316',
];

export const LEGO_COLORS = [
  { id: 0, name: '黑色', rgb: '#05131D' },
  { id: 1, name: '蓝色', rgb: '#0055BF' },
  { id: 2, name: '绿色', rgb: '#237841' },
  { id: 3, name: '深绿色', rgb: '#1B562E' },
  { id: 4, name: '红色', rgb: '#C91A09' },
  { id: 5, name: '深粉', rgb: '#C870A0' },
  { id: 6, name: '棕色', rgb: '#583927' },
  { id: 7, name: '浅灰色', rgb: '#9BA19D' },
  { id: 8, name: '深灰色', rgb: '#6B7A76' },
  { id: 9, name: '浅蓝灰色', rgb: '#A0A5A9' },
  { id: 10, name: '深蓝灰色', rgb: '#6C6E68' },
  { id: 11, name: '白色', rgb: '#FFFFFF' },
  { id: 12, name: '黄色', rgb: '#F2CD37' },
  { id: 13, name: '浅绿色', rgb: '#96C92E' },
  { id: 14, name: '青绿色', rgb: '#44B8A8' },
  { id: 15, name: '亮粉色', rgb: '#FC97AC' },
  { id: 16, name: '橙色', rgb: '#FE8A18' },
  { id: 17, name: '金色', rgb: '#DBAC34' },
  { id: 18, name: '珍珠金色', rgb: '#AA7F2E' },
  { id: 19, name: '亮紫色', rgb: '#81007B' },
  { id: 20, name: '深蓝色', rgb: '#003A70' },
  { id: 21, name: '深蓝色', rgb: '#003A70' },
  { id: 22, name: '中蓝色', rgb: '#5A93DB' },
  { id: 23, name: '酒红色', rgb: '#720E0F' },
  { id: 24, name: '红棕色', rgb: '#832013' },
  { id: 25, name: '紫色', rgb: '#3F3691' },
  { id: 26, name: '透明', rgb: '#FFFFFF' },
  { id: 27, name: '透明红', rgb: '#C91A09' },
  { id: 28, name: '透明蓝', rgb: '#0020A0' },
  { id: 29, name: '透明荧光绿', rgb: '#D9E4A7' },
  { id: 30, name: '透明绿', rgb: '#42B6C9' },
  { id: 31, name: '透明紫', rgb: '#A5F2F3' },
  { id: 32, name: '透明粉色', rgb: '#E6ADC8' },
  { id: 33, name: '透明橙色', rgb: '#F8BB3D' },
  { id: 34, name: '荧光橙色', rgb: '#FF7900' },
  { id: 35, name: '荧光粉色', rgb: '#FF5BA1' },
  { id: 36, name: '荧光黄色', rgb: '#F6F653' },
  { id: 37, name: '亮绿色', rgb: '#BBE90B' },
  { id: 38, name: '亮橙红色', rgb: '#FF4B00' },
  { id: 39, name: '橄榄绿色', rgb: '#9B9A5A' },
  { id: 40, name: '沙绿色', rgb: '#A0BCAC' },
  { id: 41, name: '沙紫色', rgb: '#6E688A' },
  { id: 42, name: '沙蓝色', rgb: '#8E9CBE' },
  { id: 43, name: '沙白色', rgb: '#FCFCFC' },
  { id: 44, name: '浅米色', rgb: '#E4D9B0' },
  { id: 45, name: '红褐色', rgb: '#94724A' },
  { id: 46, name: '珊瑚色', rgb: '#FF8480' },
  { id: 47, name: '粉色', rgb: '#FFA5A5' },
  { id: 48, name: '深棕色', rgb: '#402A1D' },
  { id: 49, name: '红棕色', rgb: '#832013' },
  { id: 50, name: '中棕色', rgb: '#836039' },
  { id: 51, name: '中黄色', rgb: '#F1D02E' },
  { id: 52, name: '亮橙色', rgb: '#FB8300' },
  { id: 53, name: '天蓝色', rgb: '#87C0EA' },
  { id: 54, name: '青色', rgb: '#00FFFE' },
  { id: 55, name: '亮青色', rgb: '#00FFFE' },
  { id: 56, name: '透明黄', rgb: '#DAB000' },
  { id: 57, name: '透明蓝', rgb: '#0055BF' },
  { id: 58, name: '透明荧光橙', rgb: '#F5CD47' },
  { id: 59, name: '透明火焰黄色', rgb: '#FFE055' },
  { id: 60, name: '透明蓝绿色', rgb: '#65C2A8' },
  { id: 61, name: '透明深蓝色', rgb: '#2C58A7' },
  { id: 62, name: '透明紫色', rgb: '#6874CA' },
  { id: 63, name: '非常浅的粉色', rgb: '#FFB6C1' },
  { id: 64, name: '非常浅的蓝色', rgb: '#B4D2E3' },
  { id: 65, name: '非常浅的绿色', rgb: '#CCDA88' },
  { id: 66, name: '非常浅的紫色', rgb: '#C393E0' },
  { id: 67, name: '非常浅的橙色', rgb: '#FFD396' },
  { id: 68, name: '非常浅的棕色', rgb: '#E5CD9F' },
  { id: 69, name: '非常浅的灰色', rgb: '#E6E3E0' },
  { id: 70, name: '金属蓝色', rgb: '#708E9C' },
  { id: 71, name: '银色', rgb: '#C9CAC4' },
  { id: 72, name: '银色', rgb: '#C9CAC4' },
  { id: 73, name: '银色', rgb: '#C9CAC4' },
  { id: 74, name: '银色', rgb: '#C9CAC4' },
  { id: 75, name: '铜色', rgb: '#AE7A51' },
  { id: 76, name: '铜色', rgb: '#AE7A51' },
  { id: 77, name: '铜色', rgb: '#AE7A51' },
  { id: 78, name: '铜色', rgb: '#AE7A51' },
  { id: 79, name: '珍珠金色', rgb: '#AA7F2E' },
  { id: 80, name: '珍珠金色', rgb: '#AA7F2E' },
  { id: 81, name: '珍珠金色', rgb: '#AA7F2E' },
  { id: 82, name: '珍珠金色', rgb: '#AA7F2E' },
  { id: 83, name: '珍珠金色', rgb: '#AA7F2E' },
  { id: 84, name: '白色', rgb: '#FFFFFF' },
  { id: 85, name: '透明', rgb: '#FFFFFF' },
  { id: 86, name: '透明', rgb: '#FFFFFF' },
  { id: 87, name: '透明', rgb: '#FFFFFF' },
  { id: 88, name: '透明', rgb: '#FFFFFF' },
  { id: 89, name: '透明', rgb: '#FFFFFF' },
  { id: 90, name: '金属绿色', rgb: '#8EA382' },
  { id: 91, name: '金属粉色', rgb: '#E4A0A0' },
  { id: 92, name: '金属粉色', rgb: '#E4A0A0' },
  { id: 93, name: '金属粉色', rgb: '#E4A0A0' },
  { id: 94, name: '金属粉色', rgb: '#E4A0A0' },
  { id: 95, name: '金属蓝色', rgb: '#708E9C' },
  { id: 96, name: '金属蓝色', rgb: '#708E9C' },
  { id: 97, name: '金属蓝色', rgb: '#708E9C' },
  { id: 98, name: '金色', rgb: '#DBAC34' },
  { id: 99, name: '金色', rgb: '#DBAC34' },
  { id: 100, name: '金色', rgb: '#DBAC34' },
];

export const MENU_ITEMS = [
  {
    id: 'dashboard',
    label: '仪表盘',
    icon: 'LayoutDashboard',
    path: '/',
  },
  {
    id: 'collection',
    label: '收藏管理',
    icon: 'Package',
    path: '/collection',
  },
  {
    id: 'inventory',
    label: '零件库存',
    icon: 'Boxes',
    path: '/inventory',
  },
  {
    id: 'projects',
    label: '项目管理',
    icon: 'FolderKanban',
    path: '/projects',
  },
  {
    id: 'gallery',
    label: '作品展示',
    icon: 'Image',
    path: '/gallery',
  },
  {
    id: 'analytics',
    label: '数据分析',
    icon: 'BarChart3',
    path: '/analytics',
  },
];
