import type {
  DevLogEntry,
  GameVersion,
  TestPlan,
  BugReport,
  BetaTestSession,
  PlatformResearch,
  PricingStrategy,
  MarketingCampaign,
  ProjectSettings,
} from "@/types";

const today = new Date().toISOString().split("T")[0];
const daysAgo = (n: number) => {
  const d = new Date();
  d.setDate(d.getDate() - n);
  return d.toISOString().split("T")[0];
};

export const defaultProjectSettings: ProjectSettings = {
  projectName: "暗影迷途",
  description: "一款融合roguelike与metroidvania的2D动作冒险游戏，在黑暗中探索未知的地下世界",
  engine: "Godot 4.2",
  targetPlatforms: ["Steam", "Epic Games Store", "Nintendo Switch"],
  teamMembers: [
    { id: "m1", name: "夜鹰", email: "night@dev.com", role: "主程序", avatarUrl: "" },
    { id: "m2", name: "墨染", email: "ink@dev.com", role: "美术", avatarUrl: "" },
    { id: "m3", name: "清歌", email: "song@dev.com", role: "音效", avatarUrl: "" },
  ],
};

export const mockDevLogs: DevLogEntry[] = [
  {
    id: "dl1",
    date: daysAgo(0),
    completedFeatures: ["优化角色跳跃手感", "新增空中冲刺动画"],
    technicalChallenges: ["跳跃缓冲时间难以精确调整，手感偏硬"],
    solutions: ["引入土狼时间(Coyote Time)机制，配合输入缓冲(Input Buffer)解决问题"],
    hoursSpent: 6.5,
    moodIndex: 4,
    moodNote: "跳跃手感终于调到满意了，冲刺动画也很流畅！",
    createdAt: daysAgo(0) + "T22:00:00Z",
    updatedAt: daysAgo(0) + "T22:00:00Z",
  },
  {
    id: "dl2",
    date: daysAgo(1),
    completedFeatures: ["实现地图房间连接逻辑", "完成小地图渲染"],
    technicalChallenges: ["程序化生成地图时出现房间重叠问题"],
    solutions: ["使用BSP树分割算法确保房间不重叠，添加最小间距检查"],
    hoursSpent: 8,
    moodIndex: 3,
    moodNote: "BSP算法调试了一整天，但结果还不错",
    createdAt: daysAgo(1) + "T23:30:00Z",
    updatedAt: daysAgo(1) + "T23:30:00Z",
  },
  {
    id: "dl3",
    date: daysAgo(2),
    completedFeatures: ["完成Boss战第一阶段AI", "添加Boss血条UI"],
    technicalChallenges: ["Boss攻击模式切换时出现动画卡顿"],
    solutions: ["使用动画状态机的过渡时间参数，避免突兀切换"],
    hoursSpent: 7,
    moodIndex: 5,
    moodNote: "Boss战打起来超爽！自己测试都停不下来",
    createdAt: daysAgo(2) + "T21:00:00Z",
    updatedAt: daysAgo(2) + "T21:00:00Z",
  },
  {
    id: "dl4",
    date: daysAgo(3),
    completedFeatures: ["实现物品背包系统", "添加3种消耗品"],
    technicalChallenges: ["背包排序和筛选逻辑复杂"],
    solutions: ["使用观察者模式解耦UI和数据层，按类型+稀有度排序"],
    hoursSpent: 5,
    moodIndex: 3,
    moodNote: "背包系统比想象中复杂，需要继续优化",
    createdAt: daysAgo(3) + "T20:00:00Z",
    updatedAt: daysAgo(3) + "T20:00:00Z",
  },
  {
    id: "dl5",
    date: daysAgo(5),
    completedFeatures: ["添加环境音效系统", "实现动态音乐切换"],
    technicalChallenges: ["多音轨同时播放导致性能下降"],
    solutions: ["使用音频总线(Audio Bus)管理，限制同时播放的环境音数量"],
    hoursSpent: 4,
    moodIndex: 4,
    moodNote: "音效系统效果很好，洞穴的回声效果很有氛围",
    createdAt: daysAgo(5) + "T19:00:00Z",
    updatedAt: daysAgo(5) + "T19:00:00Z",
  },
  {
    id: "dl6",
    date: daysAgo(7),
    completedFeatures: ["实现存档系统", "添加自动存档功能"],
    technicalChallenges: ["存档数据序列化导致存档文件过大"],
    solutions: ["只存储变化的差异数据，使用压缩算法减小文件体积"],
    hoursSpent: 6,
    moodIndex: 2,
    moodNote: "存档系统太枯燥了，但是必须做好...",
    createdAt: daysAgo(7) + "T22:00:00Z",
    updatedAt: daysAgo(7) + "T22:00:00Z",
  },
  {
    id: "dl7",
    date: daysAgo(10),
    completedFeatures: ["完成角色技能树UI", "实现5个主动技能"],
    technicalChallenges: ["技能树连线渲染性能差"],
    solutions: ["使用Canvas绘制连线替代DOM元素，配合虚拟滚动"],
    hoursSpent: 9,
    moodIndex: 4,
    moodNote: "技能系统终于做完了，接下来可以专注关卡设计了",
    createdAt: daysAgo(10) + "T23:00:00Z",
    updatedAt: daysAgo(10) + "T23:00:00Z",
  },
  {
    id: "dl8",
    date: daysAgo(14),
    completedFeatures: ["搭建游戏主框架", "实现基础角色控制器"],
    technicalChallenges: ["物理引擎与动画系统同步问题"],
    solutions: ["使用固定时间步(Fixed Timestep)更新物理，动画独立更新"],
    hoursSpent: 10,
    moodIndex: 5,
    moodNote: "项目正式启动！充满干劲！",
    createdAt: daysAgo(14) + "T20:00:00Z",
    updatedAt: daysAgo(14) + "T20:00:00Z",
  },
];

export const mockVersions: GameVersion[] = [
  {
    id: "v1",
    versionNumber: "0.1.0",
    releaseDate: daysAgo(14),
    isMilestone: true,
    milestoneLabel: "首个可玩原型",
    newFeatures: ["基础角色控制器", "简单场景", "碰撞检测"],
    fixedBugs: [],
    releaseChecklist: [
      { id: "c1", text: "核心玩法循环可运行", completed: true, category: "testing" },
      { id: "c2", text: "无崩溃Bug", completed: true, category: "testing" },
      { id: "c3", text: "截图素材准备", completed: true, category: "marketing" },
    ],
    userFeedbacks: [
      { id: "f1", versionId: "v1", rating: 3, comment: "基础手感不错，需要更多内容", source: "内测", date: daysAgo(13) },
      { id: "f2", versionId: "v1", rating: 4, comment: "跳跃很爽，期待后续", source: "朋友", date: daysAgo(12) },
    ],
    createdAt: daysAgo(14) + "T20:00:00Z",
  },
  {
    id: "v2",
    versionNumber: "0.2.0",
    releaseDate: daysAgo(10),
    isMilestone: true,
    milestoneLabel: "技能系统完成",
    newFeatures: ["技能树系统", "5个主动技能", "技能升级机制"],
    fixedBugs: ["修复角色卡墙Bug", "修复技能冷却不重置问题"],
    releaseChecklist: [
      { id: "c4", text: "所有技能可正常释放", completed: true, category: "testing" },
      { id: "c5", text: "技能UI显示正确", completed: true, category: "testing" },
      { id: "c6", text: "录制技能演示视频", completed: true, category: "marketing" },
    ],
    userFeedbacks: [
      { id: "f3", versionId: "v2", rating: 4, comment: "技能树设计很有深度", source: "Discord社区", date: daysAgo(9) },
      { id: "f4", versionId: "v2", rating: 5, comment: "技能组合太好玩了！", source: "内测", date: daysAgo(8) },
    ],
    createdAt: daysAgo(10) + "T23:00:00Z",
  },
  {
    id: "v3",
    versionNumber: "0.3.0",
    releaseDate: daysAgo(5),
    isMilestone: true,
    milestoneLabel: "音效系统上线",
    newFeatures: ["环境音效系统", "动态音乐切换", "战斗音效"],
    fixedBugs: ["修复音效延迟播放问题", "修复多音轨性能问题"],
    releaseChecklist: [
      { id: "c7", text: "音效无杂音和爆音", completed: true, category: "testing" },
      { id: "c8", text: "不同区域音乐平滑切换", completed: true, category: "testing" },
      { id: "c9", text: "Steam商店页面更新", completed: false, category: "submission" },
    ],
    userFeedbacks: [
      { id: "f5", versionId: "v3", rating: 5, comment: "洞穴回声效果太棒了，沉浸感拉满", source: "Discord社区", date: daysAgo(4) },
    ],
    createdAt: daysAgo(5) + "T19:00:00Z",
  },
  {
    id: "v4",
    versionNumber: "0.4.0",
    releaseDate: today,
    isMilestone: false,
    milestoneLabel: "",
    newFeatures: ["背包系统", "消耗品", "Boss战第一阶段AI", "Boss血条UI"],
    fixedBugs: ["修复背包物品排序异常"],
    releaseChecklist: [
      { id: "c10", text: "Boss战完整体验", completed: false, category: "testing" },
      { id: "c11", text: "背包系统稳定性测试", completed: false, category: "testing" },
      { id: "c12", text: "提交Steam更新", completed: false, category: "submission" },
      { id: "c13", text: "Boss战实机录制", completed: false, category: "marketing" },
    ],
    userFeedbacks: [],
    createdAt: today + "T22:00:00Z",
  },
];

export const mockTestPlans: TestPlan[] = [
  {
    id: "tp1",
    name: "核心玩法测试",
    description: "验证角色控制、战斗系统、技能释放等核心功能",
    scenarios: [
      { id: "ts1", name: "角色移动", steps: ["按方向键移动", "按跳跃键跳跃", "按冲刺键冲刺"], expectedResult: "角色响应流畅，无明显延迟", status: "pass" },
      { id: "ts2", name: "技能释放", steps: ["打开技能树", "选择技能", "释放技能"], expectedResult: "技能动画播放，伤害计算正确", status: "pass" },
      { id: "ts3", name: "Boss战", steps: ["进入Boss房间", "攻击Boss", "被Boss攻击"], expectedResult: "Boss AI正常，伤害判定正确", status: "fail" },
    ],
    status: "in_progress",
    assignee: "夜鹰",
    deadline: daysAgo(2),
    createdAt: daysAgo(7),
  },
  {
    id: "tp2",
    name: "音效系统测试",
    description: "验证环境音效、动态音乐、战斗音效功能",
    scenarios: [
      { id: "ts4", name: "环境音效", steps: ["进入洞穴区域", "进入森林区域"], expectedResult: "环境音效随区域切换", status: "pass" },
      { id: "ts5", name: "战斗音乐", steps: ["进入战斗状态", "脱离战斗"], expectedResult: "音乐动态切换，无突兀中断", status: "pass" },
    ],
    status: "completed",
    assignee: "清歌",
    deadline: daysAgo(5),
    createdAt: daysAgo(10),
  },
];

export const mockBugs: BugReport[] = [
  {
    id: "b1",
    title: "Boss战第二阶段切换时游戏崩溃",
    description: "Boss血量降至50%时触发阶段切换，游戏直接闪退",
    reproductionSteps: ["进入Boss战", "将Boss血量打到50%", "观察阶段切换"],
    severity: "crash",
    status: "open",
    assignee: "夜鹰",
    versionId: "v4",
    createdAt: daysAgo(1),
    resolvedAt: null,
  },
  {
    id: "b2",
    title: "背包界面物品图标显示错误",
    description: "消耗品图标与实际物品不匹配",
    reproductionSteps: ["打开背包", "查看消耗品栏"],
    severity: "cosmetic",
    status: "in_progress",
    assignee: "墨染",
    versionId: "v4",
    createdAt: daysAgo(1),
    resolvedAt: null,
  },
  {
    id: "b3",
    title: "技能冷却时间偶尔不重置",
    description: "在特定操作顺序下，技能冷却完成后仍无法释放",
    reproductionSteps: ["释放技能A", "冷却结束瞬间释放技能B", "尝试再次释放技能A"],
    severity: "experience",
    status: "open",
    assignee: "夜鹰",
    versionId: "v3",
    createdAt: daysAgo(3),
    resolvedAt: null,
  },
  {
    id: "b4",
    title: "存档加载后角色位置偏移",
    description: "读档后角色会出现在存档点附近而非精确位置",
    reproductionSteps: ["保存游戏", "退出到主菜单", "加载存档"],
    severity: "experience",
    status: "resolved",
    assignee: "夜鹰",
    versionId: "v3",
    createdAt: daysAgo(5),
    resolvedAt: daysAgo(3),
  },
  {
    id: "b5",
    title: "小地图上房间图标偶尔闪烁",
    description: "在房间之间移动时，小地图图标会短暂消失再出现",
    reproductionSteps: ["进入新房间", "观察小地图"],
    severity: "cosmetic",
    status: "wont_fix",
    assignee: "夜鹰",
    versionId: "v2",
    createdAt: daysAgo(8),
    resolvedAt: null,
  },
  {
    id: "b6",
    title: "击败敌人后掉落物悬浮在空中",
    description: "部分敌人被击杀后掉落物不落到地面",
    reproductionSteps: ["击杀飞行敌人", "观察掉落物"],
    severity: "experience",
    status: "open",
    assignee: "夜鹰",
    versionId: "v4",
    createdAt: daysAgo(0),
    resolvedAt: null,
  },
];

export const mockBetaSessions: BetaTestSession[] = [
  {
    id: "bs1",
    name: "第一轮内测",
    testers: [
      { id: "bt1", name: "星辰", email: "star@test.com", invitationStatus: "accepted", feedback: "核心玩法很有趣，但Boss战需要更多提示", rating: 4 },
      { id: "bt2", name: "暗月", email: "moon@test.com", invitationStatus: "accepted", feedback: "音效氛围很棒，跳跃手感极佳", rating: 5 },
      { id: "bt3", name: "霜叶", email: "frost@test.com", invitationStatus: "accepted", feedback: "技能组合很爽，希望有更多技能", rating: 4 },
      { id: "bt4", name: "风铃", email: "wind@test.com", invitationStatus: "declined", feedback: "", rating: 0 },
      { id: "bt5", name: "雷鸣", email: "thunder@test.com", invitationStatus: "pending", feedback: "", rating: 0 },
    ],
    startDate: daysAgo(6),
    endDate: daysAgo(3),
    summaryNotes: "整体评价积极，核心玩法获得认可。需要加强Boss战的引导设计。",
  },
];

export const mockPlatforms: PlatformResearch[] = [
  {
    id: "p1",
    platformName: "Steam",
    listingRequirements: ["Steam Direct费用$100", "商店页面素材(截图/视频/描述)", "年龄评级", "定价设定"],
    revenueShare: "70/30 (开发者/Steam)",
    userDemographics: "核心玩家为主，偏好独立游戏和创新玩法",
    feeStructure: "收入超过$5000万后分成比例调整为75/25，超过$1亿调整为80/20",
    rating: 5,
    notes: "首选平台，用户群体最匹配，Wish List功能有利于发售前蓄力",
  },
  {
    id: "p2",
    platformName: "Epic Games Store",
    listingRequirements: ["提交申请审核", "商店素材(截图/视频)", "EULA"],
    revenueShare: "88/12 (开发者/Epic)",
    userDemographics: "年轻玩家较多，免费游戏用户基数大",
    feeStructure: "固定88/12分成，无阶梯调整",
    rating: 4,
    notes: "分成比例最优，但用户基数和发现性不如Steam",
  },
  {
    id: "p3",
    platformName: "Nintendo Switch",
    listingRequirements: ["开发者账号注册", "开发套件申请", "任天堂审核", "年龄评级"],
    revenueShare: "约70/30 (开发者/任天堂)",
    userDemographics: "休闲与核心玩家并重，偏好掌机体验",
    feeStructure: "标准30%平台费用，实体卡带另计",
    rating: 3,
    notes: "需要额外适配工作，但Switch用户对独立游戏接受度高",
  },
  {
    id: "p4",
    platformName: "GOG",
    listingRequirements: ["GOG审核", "无DRM承诺", "商店素材"],
    revenueShare: "70/30 (开发者/GOG)",
    userDemographics: "怀旧玩家和DRM-free支持者",
    feeStructure: "标准30%平台费用",
    rating: 2,
    notes: "审核严格，用户群较小但忠诚度高",
  },
];

export const mockPricingStrategies: PricingStrategy[] = [
  {
    id: "ps1",
    name: "标准定价",
    basePrice: 68,
    discountTiers: [
      { label: "首发折扣", percentage: 10, condition: "发售首周" },
      { label: "节日促销", percentage: 25, condition: "Steam大型促销" },
      { label: "年度最低", percentage: 40, condition: "发售满一年后" },
    ],
    competitorPrices: [
      { gameName: "空洞骑士", price: 48, platform: "Steam" },
      { gameName: "奥日与黑暗森林", price: 68, platform: "Steam" },
      { gameName: "死亡细胞", price: 78, platform: "Steam" },
      { gameName: "哈迪斯", price: 78, platform: "Steam" },
    ],
    decisionNotes: "68元定价在同类游戏中处于中间偏低位置，符合独立游戏定位，首发9折有助于冲销量",
    decidedAt: daysAgo(3),
  },
  {
    id: "ps2",
    name: "早鸟定价",
    basePrice: 48,
    discountTiers: [
      { label: "抢先体验折扣", percentage: 15, condition: "EA阶段" },
      { label: "正式版恢复原价", percentage: 0, condition: "1.0正式发布" },
    ],
    competitorPrices: [
      { gameName: "雨中冒险2(EA)", price: 48, platform: "Steam" },
      { gameName: "泰拉瑞亚(EA)", price: 36, platform: "Steam" },
    ],
    decisionNotes: "EA期间低价吸引核心用户，正式版恢复68元。风险：可能被贴上'廉价游戏'标签",
    decidedAt: daysAgo(1),
  },
];

export const mockCampaigns: MarketingCampaign[] = [
  {
    id: "mc1",
    name: "Steam商店页上线",
    platform: "Steam",
    budget: 0,
    startDate: daysAgo(12),
    endDate: daysAgo(12),
    impressions: 1500,
    conversions: 230,
    revenue: 0,
    status: "completed",
    notes: "商店页上线首日获得230个Wish List，超过预期",
  },
  {
    id: "mc2",
    name: "Discord社区推广",
    platform: "Discord",
    budget: 0,
    startDate: daysAgo(10),
    endDate: daysAgo(3),
    impressions: 800,
    conversions: 150,
    revenue: 0,
    status: "completed",
    notes: "在3个独立游戏Discord服务器分享开发日志，获得150个关注者",
  },
  {
    id: "mc3",
    name: "B站开发日志系列",
    platform: "Bilibili",
    budget: 500,
    startDate: daysAgo(7),
    endDate: daysAgo(0),
    impressions: 5200,
    conversions: 380,
    revenue: 0,
    status: "active",
    notes: "已发布3期开发日志视频，累计播放5200次，粉丝增长380人",
  },
  {
    id: "mc4",
    name: "Steam新品节参展",
    platform: "Steam",
    budget: 2000,
    startDate: daysAgo(-7),
    endDate: daysAgo(-14),
    impressions: 0,
    conversions: 0,
    revenue: 0,
    status: "planned",
    notes: "计划参加下月Steam新品节，准备Demo版本",
  },
  {
    id: "mc5",
    name: "推特/X开发日志",
    platform: "X(Twitter)",
    budget: 300,
    startDate: daysAgo(5),
    endDate: daysAgo(-10),
    impressions: 1200,
    conversions: 85,
    revenue: 0,
    status: "active",
    notes: "每日发布开发截图和GIF，#indiedev #gamedev标签",
  },
];

export const initialMockData = {
  projectSettings: defaultProjectSettings,
  devLogs: mockDevLogs,
  versions: mockVersions,
  testPlans: mockTestPlans,
  bugs: mockBugs,
  betaSessions: mockBetaSessions,
  platforms: mockPlatforms,
  pricingStrategies: mockPricingStrategies,
  campaigns: mockCampaigns,
};
