import type {
  Conference,
  Submission,
  Review,
  Paper,
  PaperVersion,
  Collaborator,
  ChecklistItem,
  AttendancePlan,
  TravelItem,
  Presentation,
  Expense,
  Scholar,
  CollaborationIntent,
  ConferenceNote,
  Publication,
} from '../types';

const today = new Date();
const addDays = (days: number) => {
  const date = new Date(today);
  date.setDate(date.getDate() + days);
  return date.toISOString().split('T')[0];
};

export const mockConferences: Conference[] = [
  {
    id: 'conf-001',
    name: 'NeurIPS 2026',
    organizer: 'Neural Information Processing Systems Foundation',
    acceptanceRate: 25.8,
    deadline: addDays(60),
    notificationDate: addDays(120),
    publicationFee: 0,
    website: 'https://neurips.cc',
    notes: '顶级机器学习会议，需要准备 rebuttal 阶段',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'conf-002',
    name: 'ICML 2026',
    organizer: 'International Machine Learning Society',
    acceptanceRate: 27.5,
    deadline: addDays(-90),
    notificationDate: addDays(-30),
    publicationFee: 0,
    website: 'https://icml.cc',
    notes: '',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'conf-003',
    name: 'ACL 2026',
    organizer: 'Association for Computational Linguistics',
    acceptanceRate: 30.2,
    deadline: addDays(30),
    notificationDate: addDays(90),
    publicationFee: 0,
    website: 'https://acl2026.org',
    notes: 'NLP 领域顶级会议，支持长文和短文',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'conf-004',
    name: 'CVPR 2026',
    organizer: 'IEEE Computer Society',
    acceptanceRate: 23.4,
    deadline: addDays(120),
    notificationDate: addDays(180),
    publicationFee: 0,
    website: 'https://cvpr.thecvf.com',
    notes: '计算机视觉顶级会议',
    createdAt: new Date().toISOString(),
  },
];

export const mockSubmissions: Submission[] = [
  {
    id: 'sub-001',
    conferenceId: 'conf-001',
    paperId: 'paper-001',
    status: 'preparing',
    submittedAt: '',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sub-002',
    conferenceId: 'conf-002',
    paperId: 'paper-002',
    status: 'accepted',
    submittedAt: addDays(-85),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sub-003',
    conferenceId: 'conf-003',
    paperId: 'paper-003',
    status: 'under_review',
    submittedAt: addDays(-20),
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sub-004',
    conferenceId: 'conf-003',
    paperId: 'paper-004',
    status: 'rejected',
    submittedAt: addDays(-365),
    createdAt: new Date().toISOString(),
  },
];

export const mockReviews: Review[] = [
  {
    id: 'rev-001',
    submissionId: 'sub-002',
    reviewerName: '匿名审稿人 1',
    comments: '这篇论文提出了一种新颖的方法来解决...，实验设计合理，结果令人信服。',
    suggestions: '建议在讨论部分增加与更多相关工作的比较。',
    score: 8,
    decision: 'accept',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rev-002',
    submissionId: 'sub-002',
    reviewerName: '匿名审稿人 2',
    comments: '方法扎实，创新点明确，实验结果支持了作者的主张。',
    suggestions: '可以考虑增加一个 ablation study 来验证各组件的贡献。',
    score: 7,
    decision: 'accept',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'rev-003',
    submissionId: 'sub-004',
    reviewerName: '匿名审稿人 1',
    comments: '问题有趣，但方法的创新性有限，与已有工作相比优势不明显。',
    suggestions: '建议加强理论分析或增加更多实验来证明方法的优越性。',
    score: 4,
    decision: 'reject',
    createdAt: new Date().toISOString(),
  },
];

export const mockPapers: Paper[] = [
  {
    id: 'paper-001',
    title: '基于 Transformer 的多模态学习新方法',
    abstract: '本文提出了一种新的多模态学习框架...',
    keywords: ['多模态学习', 'Transformer', '深度学习'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'paper-002',
    title: '高效的图神经网络训练策略',
    abstract: '针对大规模图数据的训练问题，我们提出了...',
    keywords: ['图神经网络', '高效训练', '采样方法'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'paper-003',
    title: '低资源语言的神经机器翻译',
    abstract: '本文研究了低资源场景下的机器翻译问题...',
    keywords: ['机器翻译', '低资源语言', '迁移学习'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'paper-004',
    title: '强化学习中的探索策略研究',
    abstract: '探索-利用权衡是强化学习中的核心问题...',
    keywords: ['强化学习', '探索策略', '贝叶斯方法'],
    createdAt: new Date().toISOString(),
  },
];

export const mockPaperVersions: PaperVersion[] = [
  {
    id: 'pv-001',
    paperId: 'paper-001',
    version: 'Draft v1',
    filePath: '',
    changes: '初始版本，完成了方法部分',
    createdAt: addDays(-30),
  },
  {
    id: 'pv-002',
    paperId: 'paper-001',
    version: 'Draft v2',
    filePath: '',
    changes: '补充实验结果，修改引言',
    createdAt: addDays(-15),
  },
  {
    id: 'pv-003',
    paperId: 'paper-001',
    version: 'Draft v3',
    filePath: '',
    changes: '根据导师意见修改，准备投稿',
    createdAt: addDays(-5),
  },
  {
    id: 'pv-004',
    paperId: 'paper-002',
    version: 'Final',
    filePath: '',
    changes: '相机就绪版本',
    createdAt: addDays(-10),
  },
];

export const mockCollaborators: Collaborator[] = [
  {
    id: 'collab-001',
    paperId: 'paper-001',
    name: '张明',
    affiliation: '清华大学',
    role: 'author',
    responsibilities: ['写作', '实验设计'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'collab-002',
    paperId: 'paper-001',
    name: '李华',
    affiliation: '清华大学',
    role: 'corresponding',
    responsibilities: ['方法设计', '审稿回复'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'collab-003',
    paperId: 'paper-001',
    name: '王教授',
    affiliation: '清华大学',
    role: 'advisor',
    responsibilities: ['指导', '资金支持'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'collab-004',
    paperId: 'paper-002',
    name: '陈芳',
    affiliation: '北京大学',
    role: 'author',
    responsibilities: ['实验', '画图'],
    createdAt: new Date().toISOString(),
  },
];

export const mockChecklistItems: ChecklistItem[] = [
  {
    id: 'check-001',
    paperId: 'paper-001',
    category: 'page_limit',
    item: '主文不超过 9 页',
    completed: true,
    notes: '当前 8 页',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'check-002',
    paperId: 'paper-001',
    category: 'citation_format',
    item: '引用格式符合 NeurIPS 要求',
    completed: true,
    notes: '使用 natbib 风格',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'check-003',
    paperId: 'paper-001',
    category: 'figure_requirements',
    item: '所有图表分辨率不低于 300dpi',
    completed: false,
    notes: '需要检查 Figure 3',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'check-004',
    paperId: 'paper-001',
    category: 'other',
    item: '补充材料已准备',
    completed: false,
    notes: '',
    createdAt: new Date().toISOString(),
  },
];

export const mockAttendancePlans: AttendancePlan[] = [
  {
    id: 'ap-001',
    conferenceId: 'conf-002',
    submissionId: 'sub-002',
    conferenceStartDate: addDays(60),
    conferenceEndDate: addDays(65),
    createdAt: new Date().toISOString(),
  },
];

export const mockTravelItems: TravelItem[] = [
  {
    id: 'ti-001',
    attendancePlanId: 'ap-001',
    type: 'flight',
    description: '北京 → 温哥华',
    date: addDays(59),
    details: 'CA991, 16:00 出发',
    confirmed: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ti-002',
    attendancePlanId: 'ap-001',
    type: 'hotel',
    description: '温哥华会议中心酒店',
    date: addDays(59),
    details: '已预订 5 晚',
    confirmed: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ti-003',
    attendancePlanId: 'ap-001',
    type: 'presentation_time',
    description: '口头报告',
    date: addDays(62),
    details: '14:00-14:30, Room A',
    confirmed: false,
    createdAt: new Date().toISOString(),
  },
];

export const mockPresentations: Presentation[] = [
  {
    id: 'pres-001',
    attendancePlanId: 'ap-001',
    type: 'slides',
    title: '高效图神经网络训练策略',
    progress: 60,
    filePath: '',
    notes: '需要添加更多动画效果',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pres-002',
    attendancePlanId: 'ap-001',
    type: 'poster',
    title: '高效图神经网络训练策略（海报版）',
    progress: 30,
    filePath: '',
    notes: '还未开始设计',
    createdAt: new Date().toISOString(),
  },
];

export const mockExpenses: Expense[] = [
  {
    id: 'exp-001',
    attendancePlanId: 'ap-001',
    category: 'registration',
    description: '会议注册费',
    budget: 800,
    actual: 750,
    receiptPath: '',
    reimbursed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp-002',
    attendancePlanId: 'ap-001',
    category: 'travel',
    description: '往返机票',
    budget: 10000,
    actual: 8500,
    receiptPath: '',
    reimbursed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp-003',
    attendancePlanId: 'ap-001',
    category: 'accommodation',
    description: '酒店住宿',
    budget: 5000,
    actual: 4800,
    receiptPath: '',
    reimbursed: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: 'exp-004',
    attendancePlanId: 'ap-001',
    category: 'food',
    description: '餐饮',
    budget: 2000,
    actual: 0,
    receiptPath: '',
    reimbursed: false,
    createdAt: new Date().toISOString(),
  },
];

export const mockScholars: Scholar[] = [
  {
    id: 'sch-001',
    name: '刘博士',
    affiliation: '斯坦福大学',
    researchArea: '计算机视觉、多模态学习',
    email: 'liu@stanford.edu',
    phone: '+1 650-123-4567',
    website: 'https://liulab.stanford.edu',
    collaborationPotential: 'high',
    conferenceMetAt: 'ICML 2025',
    notes: '在 poster 环节深入交流，对我们的工作很感兴趣',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sch-002',
    name: 'Prof. Smith',
    affiliation: 'MIT',
    researchArea: '强化学习、元学习',
    email: 'smith@mit.edu',
    phone: '',
    website: 'https://smith.mit.edu',
    collaborationPotential: 'medium',
    conferenceMetAt: 'NeurIPS 2024',
    notes: '领域大牛，可考虑申请博士后',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'sch-003',
    name: '赵研究员',
    affiliation: '中科院自动化所',
    researchArea: '自然语言处理、知识图谱',
    email: 'zhao@ia.ac.cn',
    phone: '+86 10-12345678',
    website: '',
    collaborationPotential: 'high',
    conferenceMetAt: 'ACL 2025',
    notes: '已建立初步合作意向',
    createdAt: new Date().toISOString(),
  },
];

export const mockCollaborationIntents: CollaborationIntent[] = [
  {
    id: 'ci-001',
    scholarId: 'sch-001',
    topic: '多模态学习中的知识蒸馏',
    status: 'discussion',
    nextSteps: '准备初步实验方案，下周发邮件讨论',
    followUpDate: addDays(7),
    notes: '刘博士对这个方向很感兴趣',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'ci-002',
    scholarId: 'sch-003',
    topic: '低资源语言翻译联合研究',
    status: 'proposal',
    nextSteps: '等待对方反馈合作提案',
    followUpDate: addDays(14),
    notes: '已发送合作提案，对方正在审核',
    createdAt: new Date().toISOString(),
  },
];

export const mockConferenceNotes: ConferenceNote[] = [
  {
    id: 'cn-001',
    conferenceId: 'conf-002',
    title: 'ICML 2025 参会总结',
    content: '今年 ICML 的主题是...，印象最深的 keynote 是...， poster 环节认识了很多同行。',
    tags: ['参会总结', '趋势观察'],
    createdAt: new Date().toISOString(),
  },
  {
    id: 'cn-002',
    conferenceId: 'conf-002',
    title: '优秀论文学习笔记',
    content: '获奖论文"xxx"提出了一种新颖的方法...，核心创新点包括：1)... 2)...',
    tags: ['论文学习', '方法笔记'],
    createdAt: new Date().toISOString(),
  },
];

export const mockPublications: Publication[] = [
  {
    id: 'pub-001',
    title: 'Graph Neural Networks for Large-Scale Graph Learning',
    venue: 'ICML 2024',
    venueType: 'conference',
    year: 2024,
    citations: 45,
    link: 'https://arxiv.org/abs/...',
    doi: '10.1234/icml2024',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pub-002',
    title: 'A Survey on Multi-Modal Learning',
    venue: 'IEEE TPAMI',
    venueType: 'journal',
    year: 2024,
    citations: 120,
    link: 'https://ieee.org/...',
    doi: '10.1109/TPAMI.2024',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pub-003',
    title: 'Reinforcement Learning with Bayesian Optimization',
    venue: 'NeurIPS 2023',
    venueType: 'conference',
    year: 2023,
    citations: 78,
    link: 'https://arxiv.org/abs/...',
    doi: '10.1234/neurips2023',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'pub-004',
    title: 'Low-Resource Machine Translation Using Transfer Learning',
    venue: 'ACL 2023',
    venueType: 'conference',
    year: 2023,
    citations: 35,
    link: 'https://arxiv.org/abs/...',
    doi: '10.1234/acl2023',
    createdAt: new Date().toISOString(),
  },
];
