import { Game, CollectionItem, PlayRecord, RuleNote, Review, Expansion } from '@/types';

export const seedGames: Game[] = [
  {
    id: 'g1',
    name: '璀璨宝石',
    publisher: 'Space Cowboys',
    minPlayers: 2,
    maxPlayers: 4,
    minPlayTime: 30,
    maxPlayTime: 45,
    complexity: 2.4,
    yearPublished: 2014,
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=board%20game%20splendor%20cover%20art%20colorful%20gems%20nobles&image_size=square',
    bggId: '148228',
    description: '一款经济策略桌游，玩家通过收集宝石和购买卡牌来积累财富和声望。',
    tags: ['策略', '经济', '卡牌'],
  },
  {
    id: 'g2',
    name: '瘟疫危机',
    publisher: 'Z-Man Games',
    minPlayers: 2,
    maxPlayers: 4,
    minPlayTime: 45,
    maxPlayTime: 60,
    complexity: 2.42,
    yearPublished: 2008,
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=board%20game%20pandemic%20cover%20art%20disease%20outbreak%20globe&image_size=square',
    bggId: '30549',
    description: '一款合作类桌游，玩家扮演医疗专家，共同对抗在全球蔓延的四种传染病。',
    tags: ['合作', '策略', '主题'],
  },
  {
    id: 'g3',
    name: '卡卡颂',
    publisher: 'Hans im Gluck',
    minPlayers: 2,
    maxPlayers: 5,
    minPlayTime: 30,
    maxPlayTime: 45,
    complexity: 1.92,
    yearPublished: 2000,
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=board%20game%20carcassonne%20cover%20art%20medieval%20city%20tiles&image_size=square',
    bggId: '822',
    description: '经典的区域控制和版图建设游戏，玩家通过放置板块和米宝来占领城市、道路和农场。',
    tags: ['家庭', '策略', '区域控制'],
  },
  {
    id: 'g4',
    name: '七大奇迹',
    publisher: 'Repos Production',
    minPlayers: 2,
    maxPlayers: 7,
    minPlayTime: 30,
    maxPlayTime: 60,
    complexity: 2.33,
    yearPublished: 2010,
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=board%20game%207%20wonders%20cover%20art%20ancient%20civilizations&image_size=square',
    bggId: '68448',
    description: '一款卡牌轮抽策略游戏，玩家代表七大文明古国，通过建设奇观、发展科技和发动战争来获取胜利。',
    tags: ['卡牌', '轮抽', '文明'],
  },
  {
    id: 'g5',
    name: '展翅翱翔',
    publisher: 'Stonemaier Games',
    minPlayers: 1,
    maxPlayers: 5,
    minPlayTime: 40,
    maxPlayTime: 70,
    complexity: 2.81,
    yearPublished: 2019,
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=board%20game%20wingspan%20cover%20art%20birds%20nature&image_size=square',
    bggId: '266192',
    description: '一款引擎构筑游戏，玩家扮演鸟类保护者，在不同栖息地吸引、喂养和繁殖各种鸟类。',
    tags: ['引擎构筑', '主题', '家庭'],
  },
  {
    id: 'g6',
    name: '阿瓦隆',
    publisher: 'Indie Boards & Cards',
    minPlayers: 5,
    maxPlayers: 10,
    minPlayTime: 30,
    maxPlayTime: 45,
    complexity: 2.02,
    yearPublished: 2012,
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=board%20game%20avalon%20resistance%20cover%20art%20king%20arthur&image_size=square',
    bggId: '128882',
    description: '一款社交推理游戏，好人阵营需要完成任务，而隐藏在其中的间谍则要阻止任务成功。',
    tags: ['派对', '推理', '社交'],
  },
  {
    id: 'g7',
    name: '行动代号',
    publisher: 'Czech Games Edition',
    minPlayers: 2,
    maxPlayers: 8,
    minPlayTime: 15,
    maxPlayTime: 30,
    complexity: 1.26,
    yearPublished: 2015,
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=board%20game%20codenames%20cover%20art%20words%20spies&image_size=square',
    bggId: '178900',
    description: '一款词语联想派对游戏，两队的队长通过给出一个线索词来帮助队友猜出正确的词语。',
    tags: ['派对', '家庭', '文字'],
  },
  {
    id: 'g8',
    name: '根',
    publisher: 'Leder Games',
    minPlayers: 2,
    maxPlayers: 4,
    minPlayTime: 60,
    maxPlayTime: 90,
    complexity: 3.92,
    yearPublished: 2018,
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=board%20game%20root%20cover%20art%20forest%20animals%20war&image_size=square',
    bggId: '237182',
    description: '一款不对称战争游戏，每个派系都有独特的能力和胜利条件，在森林中争夺控制权。',
    tags: ['战棋', '不对称', '策略'],
  },
];

export const seedCollectionItems: CollectionItem[] = [
  {
    id: 'c1',
    gameId: 'g1',
    status: 'owned',
    cabinet: '主书柜',
    shelf: '第二层',
    locationNotes: '盒子略压痕',
    occasionTags: ['游戏夜', '朋友聚会'],
    dateAdded: '2024-01-15',
  },
  {
    id: 'c2',
    gameId: 'g2',
    status: 'owned',
    cabinet: '主书柜',
    shelf: '第二层',
    occasionTags: ['家庭游戏', '游戏夜'],
    dateAdded: '2024-02-20',
  },
  {
    id: 'c3',
    gameId: 'g3',
    status: 'owned',
    cabinet: '卧室书柜',
    shelf: '第一层',
    occasionTags: ['家庭游戏', '轻松局'],
    dateAdded: '2024-03-10',
  },
  {
    id: 'c4',
    gameId: 'g5',
    status: 'wishlist',
    cabinet: '',
    shelf: '',
    occasionTags: [],
    dateAdded: '2024-05-01',
  },
  {
    id: 'c5',
    gameId: 'g6',
    status: 'lent',
    cabinet: '主书柜',
    shelf: '第三层',
    locationNotes: '借给小明',
    occasionTags: [],
    dateAdded: '2024-04-15',
  },
  {
    id: 'c6',
    gameId: 'g7',
    status: 'owned',
    cabinet: '客厅收纳',
    shelf: '第一层',
    occasionTags: ['派对', '聚会'],
    dateAdded: '2024-03-25',
  },
];

export const seedPlayRecords: PlayRecord[] = [
  {
    id: 'p1',
    gameId: 'g1',
    playDate: '2024-05-28',
    duration: 35,
    players: [
      { name: '我', isWinner: true, score: 15 },
      { name: '小明', isWinner: false, score: 12 },
      { name: '小红', isWinner: false, score: 10 },
    ],
    winner: '我',
    rating: 8,
    notes: '第三回合拿到关键贵族卡锁定胜局',
  },
  {
    id: 'p2',
    gameId: 'g1',
    playDate: '2024-05-25',
    duration: 40,
    players: [
      { name: '我', isWinner: false, score: 11 },
      { name: '小明', isWinner: true, score: 14 },
      { name: '小李', isWinner: false, score: 9 },
    ],
    winner: '小明',
    rating: 7,
    notes: '小明前期发展太顺了',
  },
  {
    id: 'p3',
    gameId: 'g2',
    playDate: '2024-05-20',
    duration: 55,
    players: [
      { name: '我', isWinner: true },
      { name: '小红', isWinner: true },
      { name: '小李', isWinner: true },
    ],
    winner: '全员',
    rating: 9,
    notes: '紧张刺激的合作局，最后一刻治愈了所有疾病！',
  },
  {
    id: 'p4',
    gameId: 'g3',
    playDate: '2024-05-15',
    duration: 30,
    players: [
      { name: '我', isWinner: false, score: 98 },
      { name: '妈妈', isWinner: true, score: 112 },
    ],
    winner: '妈妈',
    rating: 8,
    notes: '妈妈的农场策略很稳健',
  },
  {
    id: 'p5',
    gameId: 'g7',
    playDate: '2024-05-10',
    duration: 20,
    players: [
      { name: '我', isWinner: true },
      { name: '小明', isWinner: true },
      { name: '小红', isWinner: false },
      { name: '小李', isWinner: false },
      { name: '小王', isWinner: false },
      { name: '小张', isWinner: false },
    ],
    winner: '蓝队',
    rating: 7,
    notes: '作为队长给出的线索很精准',
  },
  {
    id: 'p6',
    gameId: 'g1',
    playDate: '2024-05-05',
    duration: 38,
    players: [
      { name: '我', isWinner: true, score: 16 },
      { name: '小明', isWinner: false, score: 13 },
    ],
    winner: '我',
    rating: 8,
    notes: '两人局节奏更快',
  },
];

export const seedRuleNotes: RuleNote[] = [
  {
    id: 'r1',
    gameId: 'g1',
    type: 'keyPoint',
    title: '贵族获得条件',
    content: '当玩家拥有的卡牌满足贵族卡上显示的宝石类型和数量要求时，立刻获得该贵族卡。注意：只能用发展卡上的宝石，不能用持有的宝石代币。',
    tags: ['核心规则'],
    createdAt: '2024-05-01',
    updatedAt: '2024-05-01',
  },
  {
    id: 'r2',
    gameId: 'g1',
    type: 'qa',
    title: '可以购买超过自己支付能力的卡牌吗？',
    content: '不可以。购买卡牌时，玩家必须能够支付卡牌的全部费用。金色宝石可以作为万能宝石使用，但每颗金色宝石只能代替一种颜色的宝石。',
    tags: ['支付'],
    createdAt: '2024-05-02',
    updatedAt: '2024-05-02',
  },
  {
    id: 'r3',
    gameId: 'g1',
    type: 'teaching',
    title: '新手教学简化版',
    content: '第一步：解释三种动作（拿宝石、买卡、保留卡）。\n第二步：忽略贵族卡，先让玩家熟悉基础机制。\n第三步：加入贵族卡和保留规则。\n第四步：完整规则游戏。',
    tags: ['教学'],
    createdAt: '2024-05-03',
    updatedAt: '2024-05-03',
  },
  {
    id: 'r4',
    gameId: 'g2',
    type: 'keyPoint',
    title: '角色特殊能力',
    content: '调度员：可以移动其他玩家的棋子，每回合一次。\n研究员：发现治疗时可以获得额外一张城市卡。\n medic：在有疾病的城市停留时移除所有该疾病方块。\n科学家：只需要4张同色卡牌就可以研发治疗。',
    tags: ['角色', '核心规则'],
    createdAt: '2024-05-10',
    updatedAt: '2024-05-10',
  },
  {
    id: 'r5',
    gameId: 'g3',
    type: 'qa',
    title: '农场计分规则',
    content: '游戏结束时计分，一个完整的农场覆盖的城市数量决定分数。如果农场被一条河分隔，需要分开计算。每个骑士在游戏过程中可以获得的分数为占领的道路数量。',
    tags: ['计分'],
    createdAt: '2024-05-12',
    updatedAt: '2024-05-12',
  },
];

export const seedReviews: Review[] = [
  {
    id: 'rv1',
    gameId: 'g1',
    type: 'firstImpression',
    content: '规则简单但策略深度足够。宝石机制很有新意，贵族卡的引入让游戏节奏很好。美术设计精美，配件质量上乘。',
    rating: 8,
    createdAt: '2024-01-15',
  },
  {
    id: 'rv2',
    gameId: 'g1',
    type: 'secondPlay',
    content: '玩了10局后发现这个游戏的组合很多。不同的贵族卡会带来完全不同的策略。两人局和四人局的体验差异很大。',
    rating: 8.5,
    createdAt: '2024-02-01',
  },
  {
    id: 'rv3',
    gameId: 'g1',
    type: 'longTerm',
    content: '经典中的经典。虽然已经玩了50多局，但每次开起来还是很有新鲜感。策略选择多，节奏控制好，重开率高。强烈推荐给所有桌游入门玩家。',
    rating: 9,
    createdAt: '2024-05-01',
  },
  {
    id: 'rv4',
    gameId: 'g2',
    type: 'firstImpression',
    content: '合作游戏的入门必备。紧张刺激，充满成就感。但容易受到AP(分析瘫痪)影响，需要玩家们有良好的沟通节奏。',
    rating: 8.5,
    createdAt: '2024-02-20',
  },
  {
    id: 'rv5',
    gameId: 'g7',
    type: 'longTerm',
    content: '最佳派对游戏之一。规则简单，5分钟就能学会。重开率极高，每次游戏都有新的笑点。唯一缺点是对队长的词汇量要求比较高。',
    rating: 9,
    createdAt: '2024-04-01',
  },
];

export const seedExpansions: Expansion[] = [
  {
    id: 'e1',
    baseGameId: 'g1',
    name: '璀璨宝石：城市',
    publisher: 'Space Cowboys',
    yearPublished: 2017,
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=board%20game%20splendor%20cities%20expansion%20cover&image_size=square',
    status: 'wishlist',
    notes: '听说增加了更多策略选择',
  },
  {
    id: 'e2',
    baseGameId: 'g3',
    name: '卡卡颂：旅店与大教堂',
    publisher: 'Hans im Gluck',
    yearPublished: 2002,
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=board%20game%20carcassonne%20inns%20and%20cathedrals%20expansion&image_size=square',
    status: 'owned',
    notes: '经典扩展，必入',
  },
  {
    id: 'e3',
    baseGameId: 'g3',
    name: '卡卡颂：商人与建筑师',
    publisher: 'Hans im Gluck',
    yearPublished: 2003,
    coverImage: 'https://trae-api-cn.mchost.guru/api/ide/v1/text_to_image?prompt=board%20game%20carcassonne%20traders%20and%20builders%20expansion&image_size=square',
    status: 'owned',
    notes: '增加了更多得分方式',
  },
];
