import {
  TrainingRecord,
  InjuryRecord,
  Skill,
  Milestone,
  Equipment,
  Location,
  EmergencyContact,
  Goal,
  Partner,
  Trip,
  UserProfile,
} from '@/types';
import { generateId } from './storage';
import { addDays } from './dateUtils';

const today = new Date();

export const mockUser: UserProfile = {
  id: 'user_001',
  name: '张伟',
  email: 'zhangwei@example.com',
  primarySport: 'climbing',
  joinedDate: new Date(today.getFullYear() - 1, today.getMonth(), today.getDate()).toISOString(),
};

export const mockTrainingRecords: TrainingRecord[] = [
  {
    id: generateId(),
    sportType: 'climbing',
    date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2).toISOString(),
    location: '岩石先锋攀岩馆',
    duration: 120,
    details: {
      routeName: '火焰之路',
      grade: '5.11c',
      completionType: 'redpoint',
      attempts: 4,
      keyMoves: ['第3个支点需要动态移动', '第8个脚点注意平衡'],
      wallType: 'sport',
    },
    videoAnnotations: [
      {
        id: generateId(),
        timestamp: 45,
        label: '关键动作',
        description: '第3个支点的动态移动',
      },
    ],
    notes: '今天状态不错，终于红点了这条线！',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    sportType: 'climbing',
    date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5).toISOString(),
    location: '云端攀岩中心',
    duration: 90,
    details: {
      routeName: '入门坡道',
      grade: 'V3',
      completionType: 'flash',
      attempts: 1,
      keyMoves: ['注意核心收紧', '保持低重心'],
      wallType: 'bouldering',
    },
    videoAnnotations: [],
    notes: '抱石技巧有所提升',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    sportType: 'skateboarding',
    date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 7).toISOString(),
    location: '城市滑板公园',
    duration: 150,
    details: {
      locationType: 'park',
      tricks: [
        {
          id: generateId(),
          name: 'Ollie',
          attempts: 20,
          successes: 15,
          falls: 5,
          notes: '稳定度提升',
        },
        {
          id: generateId(),
          name: 'Kickflip',
          attempts: 15,
          successes: 3,
          falls: 8,
          notes: '后脚角度需要调整',
        },
      ],
    },
    videoAnnotations: [
      {
        id: generateId(),
        timestamp: 120,
        label: 'Kickflip尝试',
        description: '板几乎转了一圈',
      },
    ],
    notes: '今天练习了基础动作',
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    sportType: 'surfing',
    date: new Date(today.getFullYear(), today.getMonth() - 1, today.getDate()).toISOString(),
    location: '三亚后海',
    duration: 180,
    details: {
      waveHeight: '1.5米',
      rideTime: 8,
      maneuvers: ['Bottom turn', 'Cutback'],
      boardType: '7ft Funboard',
      conditions: '风力中等，浪形不错',
    },
    videoAnnotations: [],
    notes: '第一次成功完成Cutback！',
    createdAt: new Date().toISOString(),
  },
];

export const mockInjuryRecords: InjuryRecord[] = [
  {
    id: generateId(),
    bodyPart: '左前臂',
    severity: 'moderate',
    injuryDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 14).toISOString(),
    treatment: '休息、冰敷、物理治疗',
    status: 'recovering',
    recoveryProgress: 70,
    expectedReturn: addDays(today.toISOString().split('T')[0], 14),
    rehabilitationLogs: [
      {
        date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 10).toISOString(),
        activity: '轻度拉伸',
        painLevel: 3,
      },
      {
        date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 5).toISOString(),
        activity: '力量训练',
        painLevel: 2,
      },
    ],
    createdAt: new Date().toISOString(),
  },
  {
    id: generateId(),
    bodyPart: '右脚踝',
    severity: 'mild',
    injuryDate: new Date(today.getFullYear(), today.getMonth() - 2, today.getDate()).toISOString(),
    treatment: '休息、护踝',
    status: 'recovered',
    recoveryProgress: 100,
    expectedReturn: new Date(today.getFullYear(), today.getMonth() - 1, today.getDate()).toISOString(),
    rehabilitationLogs: [],
    createdAt: new Date().toISOString(),
  },
];

export const mockSkills: Skill[] = [
  {
    id: generateId(),
    sportType: 'climbing',
    category: '基础技术',
    skillName: '脚法控制',
    description: '精确的脚点放置和体重转移',
    currentLevel: 4,
    maxLevel: 5,
    progressPercent: 80,
    firstAttemptDate: new Date(today.getFullYear() - 1, today.getMonth(), today.getDate()).toISOString(),
    trainingSessions: 45,
    prerequisites: [],
    isUnlocked: true,
  },
  {
    id: generateId(),
    sportType: 'climbing',
    category: '基础技术',
    skillName: '平衡技巧',
    description: '在各种姿势下保持身体平衡',
    currentLevel: 3,
    maxLevel: 5,
    progressPercent: 60,
    firstAttemptDate: new Date(today.getFullYear() - 1, today.getMonth() + 1, today.getDate()).toISOString(),
    trainingSessions: 30,
    prerequisites: [],
    isUnlocked: true,
  },
  {
    id: generateId(),
    sportType: 'climbing',
    category: '进阶技术',
    skillName: '动态移动',
    description: '从一个支点跳跃到另一个支点',
    currentLevel: 2,
    maxLevel: 5,
    progressPercent: 40,
    trainingSessions: 15,
    prerequisites: ['脚法控制', '平衡技巧'],
    isUnlocked: true,
  },
  {
    id: generateId(),
    sportType: 'climbing',
    category: '进阶技术',
    skillName: '勾脚技术',
    description: '用脚勾住支点来保持平衡',
    currentLevel: 1,
    maxLevel: 5,
    progressPercent: 20,
    trainingSessions: 5,
    prerequisites: ['平衡技巧'],
    isUnlocked: false,
  },
  {
    id: generateId(),
    sportType: 'skateboarding',
    category: '基础动作',
    skillName: 'Ollie',
    description: '基础跳跃动作',
    currentLevel: 4,
    maxLevel: 5,
    progressPercent: 80,
    firstAttemptDate: new Date(today.getFullYear() - 1, today.getMonth(), today.getDate()).toISOString(),
    masteryDate: new Date(today.getFullYear(), today.getMonth() - 2, today.getDate()).toISOString(),
    trainingSessions: 60,
    prerequisites: [],
    isUnlocked: true,
  },
  {
    id: generateId(),
    sportType: 'skateboarding',
    category: '翻板动作',
    skillName: 'Kickflip',
    description: '用前脚踢板让板旋转360度',
    currentLevel: 2,
    maxLevel: 5,
    progressPercent: 40,
    firstAttemptDate: new Date(today.getFullYear(), today.getMonth() - 3, today.getDate()).toISOString(),
    trainingSessions: 25,
    prerequisites: ['Ollie'],
    isUnlocked: true,
  },
  {
    id: generateId(),
    sportType: 'surfing',
    category: '基础',
    skillName: '起板',
    description: '从趴着到站起来的动作',
    currentLevel: 5,
    maxLevel: 5,
    progressPercent: 100,
    masteryDate: new Date(today.getFullYear() - 1, today.getMonth() + 2, today.getDate()).toISOString(),
    trainingSessions: 30,
 prerequisites: [],
    isUnlocked: true,
  },
  {
    id: generateId(),
    sportType: 'surfing',
    category: '进阶',
    skillName: 'Bottom Turn',
    description: '浪壁底部的转弯',
    currentLevel: 4,
    maxLevel: 5,
    progressPercent: 80,
    trainingSessions: 20,
    prerequisites: ['起板'],
    isUnlocked: true,
  },
  {
    id: generateId(),
    sportType: 'surfing',
    category: '进阶',
    skillName: 'Cutback',
    description: '回转向浪尖',
    currentLevel: 3,
    maxLevel: 5,
    progressPercent: 60,
    trainingSessions: 12,
    prerequisites: ['起板', 'Bottom Turn'],
    isUnlocked: true,
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: generateId(),
    title: '首次完成5.10难度',
    description: '成功红点了第一条5.10路线',
    category: 'achievement',
    achievedDate: new Date(today.getFullYear() - 1, today.getMonth() + 3, today.getDate()).toISOString(),
    sportType: 'climbing',
    achievementDetails: { route: '新手入门', grade: '5.10a' },
    isPublic: true,
    icon: 'Mountain',
  },
  {
    id: generateId(),
    title: '首个稳定Ollie',
    description: 'Ollie成功率达到80%',
    category: 'skill',
    achievedDate: new Date(today.getFullYear(), today.getMonth() - 4, today.getDate()).toISOString(),
    sportType: 'skateboarding',
    achievementDetails: { attempts: 20, successes: 16 },
    isPublic: true,
    icon: 'Zap',
  },
  {
    id: generateId(),
    title: '连续训练30天',
    description: '坚持每日训练一个月',
    category: 'achievement',
    achievedDate: new Date(today.getFullYear(), today.getMonth() - 2, today.getDate()).toISOString(),
    sportType: 'climbing',
    achievementDetails: { streak: 30 },
    isPublic: false,
    icon: 'Flame',
  },
  {
    id: generateId(),
    title: '首次Cutback成功',
    description: '在浪上完成了第一个Cutback动作',
    category: 'skill',
    achievedDate: new Date(today.getFullYear(), today.getMonth() - 1, today.getDate()).toISOString(),
    sportType: 'surfing',
    achievementDetails: { waveHeight: '1.5米', board: '7ft' },
    isPublic: true,
    icon: 'Waves',
  },
];

export const mockEquipment: Equipment[] = [
  {
    id: generateId(),
    name: '攀岩安全带',
    type: 'harness',
    brand: 'Black Diamond',
    model: 'Solution',
    purchaseDate: new Date(today.getFullYear() - 1, today.getMonth(), today.getDate()).toISOString(),
    lastCheckDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 30).toISOString(),
    nextCheckDate: addDays(today.toISOString().split('T')[0], 1),
    checkIntervalDays: 30,
    condition: 'good',
    maintenanceLogs: [
      {
        date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 30).toISOString(),
        action: '常规检查',
        notes: '织带状态良好，金属件无磨损',
      },
    ],
    notes: '主力装备，每次训练都使用',
  },
  {
    id: generateId(),
    name: '攀岩头盔',
    type: 'helmet',
    brand: 'Petzl',
    model: 'Meteora',
    purchaseDate: new Date(today.getFullYear() - 2, today.getMonth(), today.getDate()).toISOString(),
    lastCheckDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 60).toISOString(),
    nextCheckDate: addDays(today.toISOString().split('T')[0], 90),
    checkIntervalDays: 90,
    condition: 'good',
    maintenanceLogs: [],
    notes: '户外必备',
  },
  {
    id: generateId(),
    name: '滑板',
    type: 'board',
    brand: 'Element',
    model: 'Section',
    purchaseDate: new Date(today.getFullYear(), today.getMonth() - 3, today.getDate()).toISOString(),
    lastCheckDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 10).toISOString(),
    nextCheckDate: addDays(today.toISOString().split('T')[0], 20),
    checkIntervalDays: 30,
    condition: 'fair',
    maintenanceLogs: [
      {
        date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 10).toISOString(),
        action: '更换轴承',
        notes: '轴承有些生锈了',
      },
    ],
    notes: '板面有划痕，但不影响使用',
  },
  {
    id: generateId(),
    name: '冲浪板',
    type: 'board',
    brand: 'Channel Islands',
    model: 'Pod Mod',
    purchaseDate: new Date(today.getFullYear() - 1, today.getMonth() + 3, today.getDate()).toISOString(),
    lastCheckDate: new Date(today.getFullYear(), today.getMonth() - 1, today.getDate()).toISOString(),
    nextCheckDate: addDays(today.toISOString().split('T')[0], 60),
    checkIntervalDays: 60,
    condition: 'excellent',
    maintenanceLogs: [],
    notes: '我的主力板，状态很好',
  },
];

export const mockLocations: Location[] = [
  {
    id: generateId(),
    name: '岩石先锋攀岩馆',
    type: 'climbing_gym',
    address: '北京市朝阳区体育路88号',
    safetyRating: 5,
    riskFactors: [
      {
        name: '地板硬度',
        severity: 'medium',
        description: '掉落时需要注意缓冲',
      },
    ],
    emergencyPlan: {
      nearestHospital: '朝阳医院',
      emergencyPhone: '120',
      evacuationRoute: '主出入口',
    },
    photos: [],
    notes: '设施完善，教练专业',
  },
  {
    id: generateId(),
    name: '城市滑板公园',
    type: 'skate_park',
    address: '上海市浦东新区世纪大道200号',
    safetyRating: 4,
    riskFactors: [
      {
        name: '坡道边缘',
        severity: 'high',
        description: 'U型池边缘有磨损',
      },
      {
        name: '人流量',
        severity: 'medium',
        description: '周末人多，注意碰撞',
      },
    ],
    emergencyPlan: {
      nearestHospital: '浦东人民医院',
      emergencyPhone: '120',
      evacuationRoute: '东门出口',
    },
    photos: [],
    notes: '设施丰富，是市区最好的滑板公园',
  },
  {
    id: generateId(),
    name: '三亚后海冲浪点',
    type: 'surf_spot',
    address: '海南省三亚市海棠区后海村',
    safetyRating: 3,
    riskFactors: [
      {
        name: '暗流',
        severity: 'high',
        description: '退潮时有暗流，新手需注意',
      },
      {
        name: '珊瑚礁',
        severity: 'medium',
        description: '近岸有珊瑚礁，注意深度',
      },
    ],
    emergencyPlan: {
      nearestHospital: '海棠湾医院',
      emergencyPhone: '120',
      evacuationRoute: '沙滩救生亭集合',
    },
    photos: [],
    notes: '适合初学者的浪点',
  },
];

export const mockEmergencyContacts: EmergencyContact[] = [
  {
    id: generateId(),
    name: '李明',
    relationship: '好友/训练伙伴',
    phone: '138-0000-1234',
    email: 'liming@example.com',
    isPrimary: true,
    medicalInfo: '知道我的保险信息和过敏史',
  },
  {
    id: generateId(),
    name: '王医生',
    relationship: '主治医生',
    phone: '139-0000-5678',
    isPrimary: false,
    medicalInfo: '运动医学专科，了解我的伤病情况',
  },
];

export const mockGoals: Goal[] = [
  {
    id: generateId(),
    title: '完成5.12c路线',
    description: '今年内红点一条5.12c难度的运动攀路线',
    sportType: 'climbing',
    category: 'skill',
    targetDate: new Date(today.getFullYear(), 11, 31).toISOString(),
    progressPercent: 65,
    status: 'active',
    milestones: [
      {
        id: generateId(),
        title: '巩固5.11b基础',
        targetDate: new Date(today.getFullYear(), 2, 31).toISOString(),
        completed: true,
        completedDate: new Date(today.getFullYear(), 2, 20).toISOString(),
      },
      {
        id: generateId(),
        title: '红点5.11d路线',
        targetDate: new Date(today.getFullYear(), 5, 30).toISOString(),
        completed: true,
        completedDate: new Date(today.getFullYear(), 5, 15).toISOString(),
      },
      {
        id: generateId(),
        title: '完成5.12a路线',
        targetDate: new Date(today.getFullYear(), 8, 31).toISOString(),
        completed: false,
      },
      {
        id: generateId(),
        title: '红点5.12c路线',
        targetDate: new Date(today.getFullYear(), 11, 31).toISOString(),
        completed: false,
      },
    ],
    createdAt: new Date(today.getFullYear(), today.getMonth() - 6, today.getDate()).toISOString(),
  },
  {
    id: generateId(),
    title: '掌握Kickflip',
    description: 'Kickflip成功率达到80%',
    sportType: 'skateboarding',
    category: 'skill',
    targetDate: new Date(today.getFullYear(), today.getMonth() + 2, today.getDate()).toISOString(),
    progressPercent: 40,
    status: 'active',
    milestones: [
      {
        id: generateId(),
        title: '板转一圈',
        targetDate: new Date(today.getFullYear(), today.getMonth() - 1, today.getDate()).toISOString(),
        completed: true,
        completedDate: new Date(today.getFullYear(), today.getMonth() - 1, today.getDate() - 5).toISOString(),
      },
      {
        id: generateId(),
        title: '成功率50%',
        targetDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 10).toISOString(),
        completed: false,
      },
      {
        id: generateId(),
        title: '成功率80%',
        targetDate: new Date(today.getFullYear(), today.getMonth() + 2, today.getDate()).toISOString(),
        completed: false,
      },
    ],
    createdAt: new Date(today.getFullYear(), today.getMonth() - 3, today.getDate()).toISOString(),
  },
  {
    id: generateId(),
    title: '三亚冲浪之旅',
    description: '去三亚进行一周的冲浪训练',
    sportType: 'surfing',
    category: 'travel',
    targetDate: new Date(today.getFullYear(), today.getMonth() + 3, 15).toISOString(),
    progressPercent: 30,
    status: 'active',
    milestones: [
      {
        id: generateId(),
        title: '确定日期',
        targetDate: new Date(today.getFullYear(), today.getMonth(), today.getDate()).toISOString(),
        completed: true,
        completedDate: new Date(today.getFullYear(), today.getMonth(), today.getDate()).toISOString(),
      },
      {
        id: generateId(),
        title: '预订住宿',
        targetDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 20).toISOString(),
        completed: false,
      },
      {
        id: generateId(),
        title: '打包装备',
        targetDate: new Date(today.getFullYear(), today.getMonth() + 3, 10).toISOString(),
        completed: false,
      },
    ],
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 7).toISOString(),
  },
];

export const mockPartners: Partner[] = [
  {
    id: generateId(),
    name: '李明',
    nickname: 'ClimberLi',
    avatar: 'bg-primary-500',
    phone: '138-0000-1234',
    email: 'liming@example.com',
    primarySport: 'climbing',
    skillLevel: 'advanced',
    achievements: [
      '完成5.13a难度路线',
      '全国攀岩公开赛第5名',
      '连续训练100天',
    ],
    notes: '老搭档，经常一起训练',
    progressHistory: [
      {
        id: generateId(),
        activity: '红点5.12b "火焰之路"',
        date: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2).toISOString(),
      },
    ],
    motivations: [
      {
        id: generateId(),
        message: '继续加油，5.13就在眼前！',
        sentAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1).toISOString(),
      },
    ],
    progressComparison: 115,
    sharedGoals: ['5.12c目标'],
    lastActivity: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 2).toISOString(),
    streak: 15,
  },
  {
    id: generateId(),
    name: '王芳',
    nickname: 'SkateQueen',
    avatar: 'bg-skate-500',
    phone: '137-0000-5678',
    primarySport: 'skateboarding',
    skillLevel: 'intermediate',
    achievements: [
      '城市滑板赛第三名',
      '掌握Heelflip',
    ],
    notes: '滑板技术很好，乐于助人',
    progressHistory: [],
    motivations: [],
    progressComparison: 90,
    sharedGoals: [],
    lastActivity: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 1).toISOString(),
    streak: 8,
  },
  {
    id: generateId(),
    name: '赵强',
    nickname: 'WaveRider',
    avatar: 'bg-surfing-500',
    phone: '136-0000-9012',
    email: 'zhaoqiang@example.com',
    primarySport: 'surfing',
    skillLevel: 'advanced',
    achievements: [
      '海南冲浪公开赛冠军',
      '挑战3米大浪',
    ],
    notes: '冲浪老手，去年一起去了泰国',
    progressHistory: [],
    motivations: [],
    progressComparison: 130,
    sharedGoals: ['三亚冲浪之旅'],
    lastActivity: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 3).toISOString(),
    streak: 0,
  },
];

export const mockTrips: Trip[] = [
  {
    id: generateId(),
    name: '阳朔攀岩之旅',
    description: '周末去阳朔挑战天然岩壁',
    location: '广西阳朔',
    sportType: 'climbing',
    category: 'weekend',
    startDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 7).toISOString(),
    endDate: new Date(today.getFullYear(), today.getMonth(), today.getDate() + 9).toISOString(),
    status: 'planned',
    estimatedCost: 3000,
    weather: 'sunny',
    safetyConsiderations: '检查装备状态，注意天气变化',
    packingList: [
      { id: generateId(), item: '安全带', checked: true },
      { id: generateId(), item: '头盔', checked: true },
      { id: generateId(), item: '镁粉袋', checked: false },
      { id: generateId(), item: '快挂10个', checked: false },
      { id: generateId(), item: '速干衣', checked: true },
      { id: generateId(), item: '登山鞋', checked: false },
    ],
    activityNotes: '计划挑战酒瓶山和大榕树两条经典路线',
    createdAt: new Date(today.getFullYear(), today.getMonth(), today.getDate() - 14).toISOString(),
  },
  {
    id: generateId(),
    name: '泰国冲浪之旅',
    description: '去年的泰国普吉岛冲浪之旅',
    location: '泰国普吉岛',
    sportType: 'surfing',
    category: 'vacation',
    startDate: new Date(today.getFullYear() - 1, 11, 20).toISOString(),
    endDate: new Date(today.getFullYear() - 1, 11, 27).toISOString(),
    status: 'completed',
    estimatedCost: 8000,
    weather: 'sunny',
    packingList: [
      { id: generateId(), item: '冲浪板', checked: true },
      { id: generateId(), item: '冲浪服', checked: true },
      { id: generateId(), item: '防晒霜', checked: true },
    ],
    activityNotes:
      '卡塔海滩的浪非常好，成功挑战了2米大浪。下次可以尝试更高难度的浪点。',
    createdAt: new Date(today.getFullYear() - 1, 10, 1).toISOString(),
  },
];
